### ISSUE TITLE
Program nejde pustit

### ISSUE THREAD

**Issue by JancaB** [hroncok/receptar#23]
Traceback (most recent call last):
  File "receptar.py", line 23, in <module>
    print(nacti_recept(NAZVY_RECEPTU[0]))
  File "receptar.py", line 14, in nacti_recept
    return f.read()
  File "C:\Users\Jana Bohacova\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 145: character maps to <undefined>

**Comment by hroncok** [comment]
Jeje, to je na Windows. Opravím to!

**Comment by hroncok** [comment]
Dej git pull a mělo by to jet.

**Comment by JancaB** [comment]
Funguje! :)
